language: php
matrix:
  include:
  - os: linux
    dist: precise
    php: "5.3"
  - os: linux
    dist: trusty
    php: "5.4"
  - os: linux
    dist: trusty
    php: "5.5"
  - os: linux
    dist: trusty
    php: "5.6"
  - os: linux
    dist: trusty
    php: "7.0"
  - os: linux
    dist: trusty
    php: "hhvm"
  - os: linux
    dist: xenial
    php: "7.0"
  - os: linux
    dist: xenial
    php: "7.1"
install:
  - composer install
after_script:
  - ./codeclimate.sh
