language: php
matrix:
  include:
  - os: linux
    dist: precise
    php: "5.3"
  - os: linux
    dist: trusty
    php: "5.4"
  - os: linux
    dist: trusty
    php: "5.5"
  - os: linux
    dist: trusty
    php: "5.6"
  - os: linux
    dist: trusty
    php: "7.0"
  - os: linux
    dist: xenial
    php: "7.1"
  - os: linux
    dist: xenial
    php: "7.2"
  - os: linux
    dist: bionic
    php: "7.3"
  - os: linux
    dist: bionic
    php: "7.4"
install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
after_script:
  - ./codeclimate.sh
