language: php
matrix:
  include:
  - os: linux
    dist: precise
    php:
      - "5.3"
  - os: linux
    dist: trusty
    php:
      - "5.4"
      - "5.5"
      - "5.6"
      - "7.0"
      - "hhvm"
  - os: linux
    dist: xenial
    php:
      - "7.0"
      - "7.1"
install:
  - composer install
after_script:
  - ./codeclimate.sh
