services:
    php:
        image: juitde/php:8.3.9
        restart: always
        environment:
            PHP_EXTENSIONS: "calendar intl opcache xdebug"
            XDEBUG_MODE: "coverage"
        working_dir: "/code/"
        volumes:
            - "../:/code/:cached"
